
[project]
name = "rag-pro2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shivam chaudhary", email = "shivamchy076@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=0.3.25",
    "langchain-community>=0.3.24",
    "langchain-groq>=0.3.2",
    "langchain-jina>=0.0.1.dev0",
    "langchain-qdrant>=0.2.1",
    "langchain-text-splitters>=0.3.8",
    "langsmith[claude-agent-sdk]>=0.1.147",
    "pypdf>=6.15.0",
    "qdrant-client>=1.19.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
rag-pro2 = "rag_pro2:main"

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"
